name: GKE - Deploy microservices to dev
on:
  push:
    branches:
      - main
    paths:
      - 'microservices/**'
      - 'common/**'
      - 'e2e/**'
      - 'utils/**'
  workflow_dispatch:

env:
  PROJECT_ID: {{cookiecutter.project_id}}
  SKAFFOLD_DEFAULT_REPO: gcr.io/{{cookiecutter.project_id}}
  SKAFFOLD_PROFILE: dev
  SKAFFOLD_NAMESPACE: default
  GKE_CLUSTER: main-cluster
  GKE_ZONE: {{cookiecutter.gcp_region}}
  KUSTOMIZE_VERSION: 4.1.3
  SKAFFOLD_VERSION: 1.29.0
  SKAFFOLD_CACHE_GCS: gs://{{cookiecutter.project_id}}.appspot.com/skaffold/cache

# cookiecutter:raw {% raw %}
jobs:
  deploy_backends:
    name: Deploy microservices to GKE cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.DEPLOYMENT_DEV_SA_KEY }}
          export_default_credentials: true

      - name: Connect to cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --region $GKE_REGION --project $PROJECT_ID

      - name: Set up Service Account
        run: |
          NAMESPACE=${SKAFFOLD_NAMESPACE} bash setup/setup_ksa.sh

      - name: Install Kustomize
        run: |
          wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v$KUSTOMIZE_VERSION/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
          sudo tar -xvf kustomize.tar.gz -C /usr/local/bin/

      - name: Install Skaffold release binary
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v$SKAFFOLD_VERSION/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/skaffold

      - name: Set default repo for Skaffold
        run: |
          skaffold config set default-repo "$SKAFFOLD_DEFAULT_REPO"

      - name: Download Skaffold cache if exists
        run: |
          gsutil cp $SKAFFOLD_CACHE_GCS ~/.skaffold/ || true

      - name: Build and deploy to cluster
        run: |
          skaffold run \
          --profile dev \
          -l commit=$GITHUB_SHA \
          --tag latest \
          --add-skaffold-labels=false

      - name: Upload Skaffold cache
        run: |
          gsutil cp ~/.skaffold/cache $SKAFFOLD_CACHE_GCS

# cookiecutter:endraw {% endraw %}
